name: Tests

on: push

jobs:
  test:
    services:
      mongodb:
        image: mongo:4.2
        ports:
          - 27017:27017

    runs-on: ubuntu-latest
    steps:
      # TODO: 3.8
      # https://github.com/actions/setup-python/issues/30
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev

    - name: Run tests
      run: |
        pipenv run pytest
